repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: clippy
    args: ['--all', '--all-features', '--', '-D', 'clippy::pedantic']
  - id: cargo-check
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.17.0
  hooks:
  - id: gitlint
- repo: https://github.com/crate-ci/typos
  rev: typos-v0.8.5
  hooks:
  - id: typos
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.30.0
  hooks:
  - id: markdownlint-fix
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    exclude: '^tests/Baseline'
  - id: end-of-file-fixer
    exclude: '^tests/Baseline|^doc/autogen|^doc/_static'
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.17.0
  hooks:
  - id: gitlint
