[package]
name = "zeek-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.72"

[dev-dependencies]
insta = "1.10.0"

[features]
default = ["jaeger"]
jaeger = ["opentelemetry", "opentelemetry-jaeger", "tracing-subscriber", "tracing-opentelemetry"]

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
eyre = "0.6.5"
log = "0.4.14"
opentelemetry = { version = "0.16.0", features = ["trace", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.15.0", features = ["reqwest_collector_client", "rt-tokio"], optional = true}
salsa = "0.16.1"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "io-std"] }
tower-lsp = "0.14.1"
tracing = "0.1.29"
tracing-opentelemetry = { version = "0.16.0", optional = true }
tracing-subscriber = { version = "0.3.5", features = ["tracing-log"], optional = true}
tree-sitter = "0.20.2"
