[package]
name = "zeek-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.72"

[dev-dependencies]
insta = "1.12.0"

[features]
default = ["jaeger"]
jaeger = ["opentelemetry", "opentelemetry-jaeger", "tracing-subscriber", "tracing-opentelemetry"]

[[bin]]
name = "zeek-language-server"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
eyre = "0.6.6"
itertools = "0.10.3"
log = "0.4.14"
lspower = "1.5.0"
opentelemetry = { version = "0.16.0", features = ["trace", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.15.0", features = ["reqwest_collector_client", "rt-tokio"], optional = true }
rust-fuzzy-search = "0.1.1"
salsa = "0.16.1"
tokio = { version = "1.16.0", features = ["macros", "rt-multi-thread", "io-std", "process", "time"] }
tracing = "0.1.29"
tracing-opentelemetry = { version = "0.16.0", optional = true }
tracing-subscriber = { version = "0.3.6", features = ["tracing-log"], optional = true }
tree-sitter = "0.20.3"
walkdir = "2.3.2"
