[package]
name = "zeek-language-server"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.73"

[dev-dependencies]
insta = "1.14.0"
tempfile = "3.3.0"

[features]
default = []
telemetry = ["opentelemetry", "opentelemetry-jaeger", "tracing-subscriber", "tracing-opentelemetry"]
profiling = ["pyroscope"]

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
eyre = "0.6.7"
futures = "0.3.21"
itertools = "0.10.3"
opentelemetry = { version = "0.17.0", features = ["trace", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.16.0", features = ["reqwest_collector_client", "rt-tokio"], optional = true }
pyroscope = { version = "0.4.0", optional = true }
regex = "1.5.5"
rust-fuzzy-search = "0.1.1"
salsa = "0.16.1"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "io-std", "io-util", "process", "time"] }
tower-lsp = { version = "0.16.0", features = ["runtime-tokio"] }
tracing = "0.1.32"
tracing-opentelemetry = { version = "0.17.2", optional = true }
tracing-subscriber = { version = "0.3.10", features = ["tracing-log"], optional = true }
tree-sitter = "0.20.6"
walkdir = "2.3.2"
