[package]
name = "zeek-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.72"

[dev-dependencies]
insta = "1.10.0"

[dependencies]
eyre = "0.6.5"
tree-sitter = "0.20.2"
