[package]
name = "zeek-language-server"
version = "0.24.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.77"
regex = "1.7.0"

[dev-dependencies]
insta = "1.21.1"
tempfile = "3.3.0"
wiremock = "0.5.15"

[features]
default = []
telemetry = ["opentelemetry", "opentelemetry-jaeger", "tracing-subscriber", "tracing-opentelemetry"]
profiling = ["pyroscope"]

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
eyre = "0.6.8"
futures = "0.3.25"
itertools = "0.10.5"
opentelemetry = { version = "0.18.0", features = ["trace", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.17.0", features = ["reqwest_collector_client", "rt-tokio"], optional = true }
path-clean = "0.1.0"
pyroscope = { version = "0.5.3", optional = true }
regex = "1.7.0"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
rust-fuzzy-search = "0.1.1"
salsa = "0.16.1"
semver = { version = "1.0.14", features = ["serde"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "io-std", "io-util", "process", "time"] }
tower-lsp = { version = "0.17.0", features = ["runtime-tokio"] }
tracing = "0.1.37"
tracing-opentelemetry = { version = "0.18.0", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["tracing-log"], optional = true, default-features = false }
tree-sitter = "0.20.9"
walkdir = "2.3.2"
