[package]
name = "zeek-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.72"

[dev-dependencies]
insta = "1.10.0"

[dependencies]
clap = { version = "3.0.6", features = ["derive"] }
clap-verbosity-flag = "0.4.0"
eyre = "0.6.5"
log = "0.4.14"
salsa = "0.16.1"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "io-std"] }
tower-lsp = "0.14.1"
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.5", features = ["tracing-log"] }
tracing-tree = "0.2.0"
tree-sitter = "0.20.2"
