[package]
name = "zeek-language-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.73"

[dev-dependencies]
insta = "1.12.0"

[features]
default = []
telemetry = ["opentelemetry", "opentelemetry-jaeger", "tracing-subscriber", "tracing-opentelemetry", "clap"]
profiling = ["pyroscope"]

[dependencies]
clap = { version = "3.1.0", features = ["derive"], optional = true }
eyre = "0.6.6"
futures = "0.3.21"
itertools = "0.10.3"
lspower = "1.5.0"
opentelemetry = { version = "0.17.0", features = ["trace", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.16.0", features = ["reqwest_collector_client", "rt-tokio"], optional = true }
pyroscope = { version = "0.3.1", optional = true }
rust-fuzzy-search = "0.1.1"
salsa = "0.16.1"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "io-std", "process", "time"] }
tracing = "0.1.30"
tracing-opentelemetry = { version = "0.17.1", optional = true }
tracing-subscriber = { version = "0.3.8", features = ["tracing-log"], optional = true }
tree-sitter = "0.20.4"
walkdir = "2.3.2"
